# app details
spring.application.name=debrief-bot
server.port=8081

# Slack configs.
slack.app.token=${SLACK_APP_TOKEN}
slack.bot.token=${SLACK_BOT_TOKEN}

# cron
app.nudge.cron=0 0 9 * * MON-FRI

# global logging level
logging.level.root=INFO
logging.level.com.ksb.feedbackbot=DEBUG
logging.file.name=logs/feedback-bot.log

# sql configs.
spring.datasource.url=jdbc:mysql://localhost:3306/deb_TestV1?useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=mysql
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true